### ISSUE TITLE
اتصال به سرور بازرگانی حین ثبت نام ، برای تایید عدم تکراری بودن کد ملی کاربر

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/baavers.ir#1]
![screen shot 2016-08-17 at 10 29 31 am](https://cloud.githubusercontent.com/assets/15094271/17726072/8754de8e-6465-11e6-98eb-8f3da2b1782f.jpg)

![screen shot 2016-08-16 at 2 37 33 pm](https://cloud.githubusercontent.com/assets/15094271/17726025/3b9cddf2-6465-11e6-8a70-800c0900a65c.jpg)

**Comment by jalal7h** [comment]
[معیارهای_لازم_جهت_درج_ر_دیتابیس_.docx](https://github.com/jalal7h/baavers.ir/files/421862/_._._._._._.docx)

[وب سرویس ثبت اطلاعات بازاریابان.docx](https://github.com/jalal7h/baavers.ir/files/421863/default.docx)

**Comment by sepahta** [comment]
بله دقیقا همیناست

**Comment by sepahta** [comment]
baavers.ir

**Comment by jalal7h** [comment]
DEMO inja bast hast : 
http://baavers.ns51.bestforweb.net/

![screen shot 2016-08-17 at 12 13 46 pm](https://cloud.githubusercontent.com/assets/15094271/17728350/1d51ad8c-6474-11e6-9f4c-83fe642e9ae6.jpg)

**Comment by sepahta** [comment]
خب این صفحه ثبت نامه درسته حالا وقتی کاربر میاد اطلاعات رو پر میکنه باید با اونوب سرویسی که توی اون فایل ورد هست بره متصل بشه و تایید بگیره که این شخص ایا جای دیگه ایی ثبت نام کرده یا نه اگر در شرکت بازرایابی شبکه ایی دیگه ایی ثبت نام کرده نتونه ثبت نام کنه اینجا و بهش اخطار بده که ثبت نام در اینجا مجاز نیست و دلیلش اینه که در شرکت دیگه ایی ثبت نام کرده

**Comment by sepahta** [comment]
http://www.adibavers.ir/
این سایت قبلی باورس هست و در حال کاره اینو ببینید
یوزر پسورد کاربری هم میدم که صفحه دفتر کار رو هم ببینید

**Comment by sepahta** [comment]
http://baavers.ir/admin
یوز پسورد سایت باورس 
admin
admin@123

و یوزر پسورد کابری در باورس
http://baavers.ir/customer/account/login/
maryam_rajabii86@yahoo.com
M01830183m

**Comment by jalal7h** [comment]
lotfan ruye version e demo kar beshe
http://baavers.ns51.bestforweb.net/

**Comment by jalal7h** [comment]
![screen shot 2016-08-17 at 1 13 34 pm](https://cloud.githubusercontent.com/assets/15094271/17730106/75a8fb86-647c-11e6-864c-e4867ed71d82.jpg)

**Comment by sepahta** [comment]
بسیار عالی

**Comment by meysam40** [comment]
مستندات ارائه شده کامل نیستند
و فاقد کد مورد نیاز برای اتصال به بازرگانی هستش
علاوه بر کد
براساس مستندات بالا ما نیازمند  به
نام کاربری شرکت و کلمه عبور شرکت در سایت بازرگانی برای اتصال هستیم

**Comment by jalal7h** [comment]
جناب نظافت
کار انجام شده است
فقط بظاهر user / pass حتما نیاز هست برای اتصال و اعلام کد ملی به بازرگانی

![screen shot 2016-08-18 at 4 53 20 pm](https://cloud.githubusercontent.com/assets/15094271/17773684/c07274f6-6564-11e6-9e42-e059842d2f27.jpg)

فاکتور این مورد برای شما ارسال شد
خبر از شما

**Comment by jalal7h** [comment]
tebghe darkhast, in mored laghv shod.
