### ISSUE TITLE
توسعه ماژول ام ال ام  در بخش نمای شماتیک

### ISSUE THREAD

**Issue by sepahta** [jalal7h/baavers.ir#2]
برای بخش بازاریابی شبکه ایی ماژول ام ال ام تمامی زیرمجموعه های کاربر را در دفتر کارش نشان میدهد در بخش  نمودار شماتیک.حالا میخوایم روی عکس نمودار شماتیک افراد گزارشی از ورود یوزر نیم و گزارش درآمد و پورسانت را مشاهده کنیم.البته این گزارش ها تولید میشود توسط ماژول اما در صفحه دیگری نمایش داده می شود

**Comment by jalal7h** [comment]
@sepahta lotfan chand mored ax + link az in bakhsh ersal konid

+ hamchenin user pass admin marbute ro bedid
albate ruye demo : 
http://baavers.ns51.bestforweb.net/

**Comment by jalal7h** [comment]
![screen shot 2016-08-17 at 12 22 01 pm](https://cloud.githubusercontent.com/assets/15094271/17728590/38ede550-6475-11e6-93e2-59f6015b484b.jpg)

**Comment by jalal7h** [comment]
tebghe darkhast in mored laghv shod.
